name: Docker build and push

on:
  push:
    branches:
      - master

jobs:
  Publish-to-docker:
    runs-on: ubuntu-latest
    env:
      DOCKER_TAG: latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      -
        name: List available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      -
        name: Docker login (needs DOCKER_USERNAME and DOCKER_PASSWORD secrets)
        run:
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Publish to docker as diyHue/core
        if:  ${{ success() && startsWith(github.repository, 'diyhue/')}}
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm/v7,linux/arm64 \
            --push \
            -f ./.build/Dockerfile \
            -t diyhue/core:$DOCKER_TAG \
            -t diyhue/core:master-$GITHUB_SHA \
            .
      -
        name: Publish to docker as github_user/github_repo
        if: ${{ success() && !startsWith(github.repository, 'diyhue/')}}
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm/v7,linux/arm64 \
            --push \
            -f ./.build/Dockerfile \
            -t $GITHUB_REPOSITORY:$DOCKER_TAG \
            -t $GITHUB_REPOSITORY:master-$GITHUB_SHA \
            .

  Run-tests:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Build docker image
        run: |
          docker build -t diyhue/core:ci -f ./.build/Dockerfile --build-arg TARGETPLATFORM=linux/amd64 .
      -
        name: Run docker image
        if: success()
        run: |
          docker run -d --name "diyhue" --network="host" -v '/mnt/hue-emulator/export/':'/opt/hue-emulator/export/':'rw' -e 'MAC=b8:27:eb:d4:dc:11' -e 'IP=192.168.1.123' -e 'DECONZ=192.168.1.111' -e 'IP_RANGE=5,6' -e 'DEBUG=true' diyhue/core:ci
          sleep 15
          docker logs diyhue
      -
        name: Cleanup
        run: |
          docker kill diyhue
          docker rm diyhue

